version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "lipo"
region = "us-east-1"
image_repositories = []
stack_name = "lipo"

[default.package.parameters]
resolve_s3 = true

